# Generated by Django 2.1.4 on 2019-01-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20190110_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='category',
            field=models.ManyToManyField(blank=True, default=None, to='landing.ProductCategory'),
        ),
    ]
