# Generated by Django 2.1.4 on 2019-01-16 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20190116_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AddField(
            model_name='questions',
            name='email',
            field=models.EmailField(blank=True, max_length=128, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='zvonki',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.ProductCategory', verbose_name='Выберете, со специалистом какого направления желаете пообщаться'),
        ),
    ]
